### ISSUE TITLE
Data for "Today" appears twice in the charts, with different values

### ISSUE THREAD

**Issue by Simek** [rn-versions/rn-versions.github.io#22]
The issue occurs for all of the charts, but it's best visible on the Expo (due to reduced set of historic data):

![bug](https://user-images.githubusercontent.com/719641/152528999-39956513-7c44-4842-b6eb-02ce72da7ae7.gif)

**Comment by NickGerleman** [comment]
I grabbed a new sample of data when I added React Native NetUI (RN targeting Office's internal UI platform). I think it should scale correctly, but both samples do show up in the chart.

**Comment by NickGerleman** [comment]
Going to close this out, since I'm not sure there is much to action on, but feel free to reopen.
