### ISSUE TITLE
Data Anomalies Around the Beginning of the Month

### ISSUE THREAD

**Issue by NickGerleman** [rn-versions/rn-versions.github.io#27]
`rn-versions` was created out of a necessity to understand how the open-source community interacts with and adopts new releases in the React Native ecosystem. It evolved from manual inspection of the [version information of the package](https://www.npmjs.com/package/react-native?activeTab=versions) published by the npmjs registry. The underlying webpage is still used instead of the [download counts API](https://github.com/npm/registry/blob/master/docs/download-counts.md), as the page shows per-version information that the API does not offer.

We noticed large spikes for specific older versions at the beginning of each month, across multiple different packages. 
<img width="448" alt="image" src="https://user-images.githubusercontent.com/835219/173753258-86b83d28-2d5d-4051-a7fc-81c92b548ed9.png">

This spike is reflected in the HTML served by the npmjs registry. E.g. we see `react-native@0.63.4` go from 51,690 downloads/week to 160,641.
1. https://raw.githubusercontent.com/rn-versions/rn-versions.github.io/main/history/react-native/2022-06-02T04_04_55.175Z.html 
<img width="445" alt="image" src="https://user-images.githubusercontent.com/835219/173754527-ae0e700d-e607-4b5b-9923-1d1544308cf3.png">

2. https://raw.githubusercontent.com/rn-versions/rn-versions.github.io/main/history/react-native/2022-06-03T03_43_31.541Z.html 
<img width="436" alt="image" src="https://user-images.githubusercontent.com/835219/173754597-1adc1bf7-a1bc-48bc-9626-52d34fb211e3.png">

In aggregate, we see about 300k extra downloads for 0.63 and 0.64. The spike is not present when isolating to newer versions, such as 0.65+ for `react-native`.
<img width="448" alt="image" src="https://user-images.githubusercontent.com/835219/173754160-c8b1711c-d419-4fd8-a4fb-40b06956bb94.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/835219/173760872-ff72789b-58df-458d-9296-9e6b7b5f72bd.png">

The spikes are absent from the total download count given on the same page, and other websites relying on the download count API, suggesting the numbers shown in per-version statistics may be anomalous. 
<img width="353" alt="image" src="https://user-images.githubusercontent.com/835219/173755112-496d5932-406f-47ce-8098-bfd3330f1bb5.png">

**Comment by kelset** [comment]
update on this: talked with some npm folks, they suggested to do this: https://github.com/npm/feedback/discussions/711 hopefully this will help us get to the bottom of this

**Comment by NickGerleman** [comment]
This seems to specifically happen for versions which were published more than a year ago. Almost right at that mark. So in the meantime, I've updated asset generation logic to ignore releases which came out more than a year ago. So these patch releases will fall off when they reach that mark. https://github.com/rn-versions/rn-versions.github.io/commit/4328676742fb7d148a1db90d99a193b6f87c6a51
